language: java
jdk:
- oraclejdk8

services:
  - docker

before_install:
- docker pull selenium/hub:latest
- docker pull selenium/node-chrome:latest

notifications:
  email:
  - krishnan.mahadevan1978@gmail.com
branches:
only:
- master
cache:
  directories:
  - "$HOME/.m2"
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc
  -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc
  -out $GPG_DIR/secring.gpg -d
- "$GPG_DIR/publish.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: BGx/CufFzVLMeWhU1XwqjP5esIbcidiXo4KabmbXjHEx0Uxaxjxm2YrV5d1oN77h0S2QofcqlhJ1QKf9dGiMesOPXDLDT66TpCbXSMNQg1EbLE+dJ3xSXO8fSkt8KRpuuRXqj8/zvXeASI8Xm2HbsuS4+vh06YfNhXBt0S2up4WT1kqeGtNUMKG2CWMqosrEby1Ymv52smK1R45P1rjaDm9IbOkDhIjFG+gOrvCipM5InO+D3U3ZPlELqvXBrznGAeuKX0Aik+Y/fvpgUYkClBLhDY3tOQ6xsIjq9XXcJTBbjJFRVeAcVfV7Io1qToPmcXIixQvQWzvKdp586ngDgkH8ADUL8PVNtKng13KaEFsTpuKIHizIdryhY/+LgzokFfsC/81EY2zgsX7uSGX/s6hoh4th2OX7UaAwKZlwvdmS6jqCJS3jtv4uXOCD8YGhPF71rlajcCAYgYPl8J/hD/aKffTBaLxxwH1WZ00iZ5Ts/KuOd+dN6qQ+f6V3hT4vA19MT7ReadB+xocflcarLQ5O/Yq4lgxsUQDNGO+v+LWZKhUZSn8KxCDD+dH46Z7oXcWsIGrTH+uT8ZmJu5rm5zran/VPKFygCwRutK27h45CdueN8oyp4ugBLIgalHDPO/qkeYcD9WGKjZ4I2Kx89vxO05pSN0Plo+QNp9Hd1pI=
  - secure: V+3i4GOyM6kn7fjzqIq+PM+BzfRlApD5x4Acr3Ard6Q/6wEqdEp/3pdea8BJcEL8vC/l2WSHNApnUBr6BBe1Br39Ne72Khn7QcV9XLvfpnXGHyHB8ec7ODVzoQBL8ZE56XIokPbBZFVDKZJa4Y0sLdNQmVKgvqp08xfDIn9NGepb2yuatEnmIfXo+1CZ/YuIaFsz74+VV3iu2iJns+YFDEM4ZvEG8XAUHXTqGRJSqteN1I2NTQWCE7Bo+Z2MNWJxcZTtizYml0DVr88uF2z51WshiHyR4f7IKoFiQlDmc2c9S1eCi+UuS5PISN0GV8U6DcZOmBurZSS2yrFvpLfeOD39UTYfPeLUz0Wa8B4tWrZ5fy14c2FlDS4fUnSU7oh3qNqp6v+bWy0nz7ND9pYdrksRbrqmECc7/yx6xzeuCgcTo8C0MxWToC599SWzoEDlZzjuOoh3ELCee5jwHmzyAi8hUIDAl6/ShCkGwBMpZH4dtVfyzOcKNTht90KfjNGFFvv1BQN87sTFilSJ77b62X/JR7nWSXqRMyTIC0f8Y5LFqo/HPaM2NpibqpiykBL/IKE+PPQxB89gpog6A/8ZXmJM5PsANgpmLES0bzYYEUoYNa/PAekCXIaojEJKduuSx+vAzCm4FX6TwbLFpF3mBNNC2vuDw6gvOtdlV8iMAxQ=
  - secure: Nk8Aed/9/8d4rTby0Nw2myfYZvQmw4GQH7xvqgfGL8TB8OoS7RX2tAZiB6XHzYMHdTiNrcPR0g9arsAB/9pru24OeQIgHC0SabBsnLw6WlEV0g0azEQQ3irs4lV2MPJURLxQAWhes/pDFUFRjO36KCLnSXzsAfrWUsTPcMBxAvjYbI2Nc0UsjkSzKebdKDMMz8eQbiYHa07WhZeWH/9KaRrtC077H+rZZKPjeSuacOxLyxWGA5j7WZYrhbCab6e24nxfDhL4DPYPVW0RvTYVrw2Lxh+LZvV8p814pVR1m2qRHGl/swYgQkhq1PNV30lwfH0qpXH0RTX72IVh2CKP5l4e2XdmWNF5n1d/yDYsWA32BVb6KtbRVTqdcSDepkIdaNGj2TYDND10CfyxenU8QWJbF3zAClC7jLNqhpc/dT4SgO23JrAiks6XBilSmWzcPeHWxo61lzj/uww9jNfWzY6POoZj7sk0w2zj6qM9rWPnSXQyq+1+jiOHRPDysQOIpri8F1an8n/GNIPnMG/JBMTWpQ9Zy8WDnzhg7LjQZMDF9gena9/OBH2J2qQGhAG74wR8WdLUppSq7J141oDmktTgPfPzhbYcDRNOe/w2L3Faimx0ORUBMSLzah9ojQu2l+Fv/oRO/TihbnZyQOjIJSZlyBJDe7DCSSgqAI2fRus=
  - secure: JfWT8BF7iDzUkDDsjVW5jIbvRETVt3iBExwdY40biUDzXuktQndjKjQJckvHgV1NAuMFdhl8x+KlMx74aGT+/BI1kP5c8vhlY3dGZJtTF8Pp00MXBWg8GysEPnVckEvI4Pn4aShYWFKdI6kHVVGqoqzGtfbJdAa06+0C0hdyGqIEzPmijdJ/s3amDAxcNZgQZH1o9wmp2N3qWaruR+miG5f3M2mPLnso/vuQm/DkDwmdLMoV6qnQn9h5As3jmOTciLh9DaybRNzdUuijiSs3XkwZbxfHfPjjIePoCbffUgI6syaNNOLcft7A7b967HA1npvXZsoX090f2n6hX+wsA88qr3PpyqT7H2Z2C0o+lKCwDcmJGmoCLJSnWoCkgb+zqqkKHyAm2JeIr8uzU4qHrwwRpYCZHZ14IhjZCmkRkzRpvOIjdEaXhQDWdsy+rU1PJjsGTGP7qlEK4W4B7EOtA3E/grthMjnHFkRBXZrYIF488pvZsCv+ecx3G4g6dzFvVuEBhxZkt4mMEJU0OPK+Gg1a4fjRgnwlto6Nw0DXV4nrb4GX3vpThdHj1IgGc+8t789LrmyrA4qHT8jCsYzUBnyfW2nRGbuu5DowxKcz8L4SLIbpi7vmyxGhWmX5ZNaZ+08tH70rZy3XNS/F/FQCZA1BJ5D0jXL6G6LK2ZhpR3Q=
  - secure: Q8a859swtXXe+Zpmkwaan1oDqFhQ7rCxdjppeGMEy++ujif74S8xNnb+bQk13vmNq6/rkEOxtFRsg0voWzNB19iEF5W69BLUhQgW24B78bIC13NbBct8ePGoQ0QxEjQO8eN87NxfLVvVH6Wk/jGLwRF9aPLAd4HlvxgcCmSATC9LYnlptbft/V2diN0Vf+TH6wqtSApJFjduEblHq6RKnwe6WYOBaHYWCKTVHL4hUywj4a75oi1SyWmoVJ5qGy1m4q5dS/d3z5FDGJ2oWEnv2/loxS1ob2lq/48/DpR8Xgf6pYwc1h3S1+Tn2MG23vrmfTs+4I/OTPtFxcAOahIzoZxmktY0M+bvSxvQBVFYHefmhzukswhULqMuLpc/mJOT5gpVOvIBgpmVdxVHdhQNt7l1VC/MlAOhDgRtUt2tKzVh6V0mLyb/9pEFp+Vk2KQwPG75SBYXXo7AjuMKSuvJV2eBut/XGGE/+uG6j87XKASjf7pp0+InIEVX55jhLX++L7t3MzC46+BoqKKIwMuKgfSX29saQjzWf2GOpTdSzWSSPvgHGrTWHEYZu5u5XV553JjttLThWANh3ReGglx/7PyZIdEL4NfawwrJEAwTUUmwuQ4NGdcU89Awt86B2NrTAUdGH2MMIIvWz/EBoMINtFPV2zfbBb43vP5mBv1m9Qw=
